server:
  port: 8765

spring:
  application:
    name: soundify-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: soundify-kibana-id
          uri: http://soundify-kibana:5601
          predicates:
            - Path=/kibana/**
        - id: soundify-grafana-id
          uri: http://soundify-grafana:3000
          predicates:
            - Path=/grafana/**
        - id: soundify-resource-service-id
          uri: lb://soundify-resource-service
          predicates:
            - Path=/resources/**
          filters:
            - name: CircuitBreaker
              args:
                name: soundify-resource-service
                fallbackUri: forward:/fallback/resource
        - id: soundify-song-service-id
          uri: lb://soundify-song-service
          predicates:
            - Path=/songs/**
          filters:
            - name: CircuitBreaker
              args:
                name: soundify-song-service
                fallbackUri: forward:/fallback/song
        - id: soundify-storage-info-service-id
          uri: lb://soundify-storage-info-service
          predicates:
            - Path=/storages/**
          filters:
            - name: CircuitBreaker
              args:
                name: soundify-storage-info-service
                fallbackUri: forward:/fallback/storages

eureka:
  client:
    registry-fetch-interval-seconds: 2 # for dev purpose
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.request]": true
        "[jvm.memory.used]": true
        "[jvm.classes.loaded]": true
        "[process.cpu.usage]": true
