server:
  port: 8085

spring:
  application:
    name: soundify-song-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/soundify_song_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 20MB
      max-file-size: 20MB
      max-request-size: 20MB
