server:
  port: 0

spring:
  application:
    name: soundify-resource-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/soundify_resource
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 20MB
      max-file-size: 20MB
      max-request-size: 20MB
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: nimda
storage:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: eu-north-1
  localstack:
    endpoint: http://localhost:4566

application:
  storage:
    type: LOCALSTACK
    bucket:
      staged: soundify_staged_storage_bucket
      permanent: soundify_permanent_storage_bucket
  rabbitmq:
    queue: soundify_queue
    exchange: soundify_exchange
    routing-key: soundify_routingKey
  storage-info-service:
    name: SOUNDIFY-STORAGE-INFO-SERVICE

resilience4j:
  circuitbreaker:
    instances:
      storageInfoService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 2s
        waitDurationInOpenState: 1m
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      storageInfoService:
        timeoutDuration: 2s

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
