server:
  port: 8080

spring:
  application:
    name: soundify-resource-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/soundify-resource
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 20MB
      max-file-size: 20MB
      max-request-size: 20MB
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: eu-north-1
    stack:
      audio: true

application:
  bucket:
      name: soundify-audio-bucket
